# Generated by Django 2.2.7 on 2020-07-20 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shop_having',
            field=models.ManyToManyField(to='user.Shop'),
        ),
    ]
